### ISSUE TITLE
import per device

### ISSUE THREAD

**Issue by PieterL75** [minitriga/Netbox-Device-Type-Library-Import#11]
Hey,

thx for this cool tool !
I would really like to see an option to only import one device, rather than all of one vendor.

I try to keep my netbox as clean as possible, so that people can't pick the wrong device.

Is that possible ?

Pieter

**Comment by ndom91** [comment]
Unfortunately vendor only at the moment. If I were you, I'd import the whole vendor then just go clean out the devices you don't need from the manufacturer overview page of device_types.

**Comment by PieterL75** [comment]
Hey,

I decided to learn python and update it myself :-)

Pull request is created,, please review and see if it is good enough for a
commit...

Pieter

Op wo 30 dec. 2020 om 20:59 schreef Nico Domino <notifications@github.com>:

**Comment by ndom91** [comment]
Wow thats great! Im sure minitriga will take a look as soon as possible.

**Comment by minitriga** [comment]
Hi @PieterL75 Looks like there are some conflicts that need resolving at the moment but looks good.
