### ISSUE TITLE
Some Ubiquiti Devices Don't import

### ISSUE THREAD

**Issue by savaloi** [minitriga/Netbox-Device-Type-Library-Import#118]
I've just run the script today to import Ubiquiti devices to my existing docker instance and noticed that some (two?) devices weren't imported. Seemingly with no errors displayed - but perhaps I'm not reading the log correctly.

The output says 118 device-types found, but only 116 imported.
I noticed that the UniFi Dream Machine Pro wasn't imported (But the UDM & UDM Pro SE were imported successfully), and another unknown device-type also wasn't imported.

I've temporarily solved this my manually importing the UDMP, but it would be good to see this fixed please.

Here's the script I ran:
docker run -e "NETBOX_URL=http://<IP>:<PORT>/" -e "NETBOX_TOKEN=<TOKEN>" -e "VENDORS=Ubiquiti" ghcr.io/minitriga/netbox-device-type-library-import > devimport.log

If it's helpful, here's the output:
[devtypeimport.log](https://github.com/netbox-community/Device-Type-Library-Import/files/13201647/devtypeimport.log)

**Comment by netravnen** [comment]
@savaloi Can be closed?

Using the latest version of the [device importer][0] and netbox 3.7.4. They are imported.

[0]: https://github.com/netbox-community/Device-Type-Library-Import/issues/118

![image](https://github.com/netbox-community/Device-Type-Library-Import/assets/1938389/da8f80f0-8d54-4535-8992-ff71f2861440)

**Comment by danner26** [comment]
@savaloi the docker image is not updated, we currently do not have a way and do not plan on figuring out a way to update it at the moment. One day we will get around to it, but it is best to use this locally
