### ISSUE TITLE
error": "duplicate key value violates unique constraint "

### ISSUE THREAD

**Issue by derekschartung** [minitriga/Netbox-Device-Type-Library-Import#125]
Fresh install of Netbox 3.7.3.  New DB.  Getting this error when running import.

`Package Installed https://github.com/netbox-community/devicetype-library.git
No Vendors Specified, Gathering All Device-Types
121 Vendors Found
2927 Device-Types Found
{"error": "duplicate key value violates unique constraint \"dcim_manufacturer_slug_key\"\nDETAIL:  Key (slug)=(watchguard) already exists.", "exception": "IntegrityError", "netbox_version": "3.7.3", "python_version": "3.11.4"}
{"manufacturer":["Related object not found using the provided attributes: {'name': 'HPE', 'slug': 'hpe'}"]}
Traceback (most recent call last):
  File "/app/nb-dt-import.py", line 853, in <module>
    main()
  File "/app/nb-dt-import.py", line 826, in main
    createDeviceTypes(deviceTypes, nb)
  File "/app/nb-dt-import.py", line 680, in createDeviceTypes
    dt.id, nb)
UnboundLocalError: local variable 'dt' referenced before assignment`

**Comment by netravnen** [comment]
https://github.com/netbox-community/devicetype-library/pull/1978 fixes this issue.

_Originally posted by @gurubert in https://github.com/netbox-community/Device-Type-Library-Import/issues/123#issuecomment-1976622782_
