### ISSUE TITLE
Fail to import device types when specifying slugs

### ISSUE THREAD

**Issue by BorisBachere** [minitriga/Netbox-Device-Type-Library-Import#137]
Example extracted from .env:

```
SLUGS=cisco-n9k-c93360yc-fx2
VENDORS=Cisco
```

Below error appends:
```
Traceback (most recent call last):
  File "/home/bbacspy8/projects2/Device-Type-Library-Import/./nb-dt-import.py", line 54, in <module>
    main()
  File "/home/bbacspy8/projects2/Device-Type-Library-Import/./nb-dt-import.py", line 32, in main
    module_types = settings.dtl_repo.parse_files(files, slugs=args.slugs)
  File "/home/bbacspy8/projects2/Device-Type-Library-Import/repo.py", line 111, in parse_files
    if slugs and True not in [
  File "/home/bbacspy8/projects2/Device-Type-Library-Import/repo.py", line 112, in <listcomp>
    True if s.casefold() in data["slug"].casefold() else False for s in slugs
KeyError: 'slug'
```

**Comment by jonkerj** [comment]
The code seems to assume module type YAML files have a key `slug`. If you comment out the part where module types are imported, it does not crash on this.

**Comment by danner26** [comment]
All files should have a slug, can you point me to one that does not?

**Comment by BorisBachere** [comment]
Actually the issue is that no file exists for N9K-C93360YC-FX2.
I created it on pull #2435

**Comment by jonkerj** [comment]
> All files should have a slug, can you point me to one that does not?

`modules-types/ZTE/PRWH.yaml`

**Comment by danner26** [comment]
> > All files should have a slug, can you point me to one that does not?
> 
> `modules-types/ZTE/PRWH.yaml`

Sorry about that, was speaking about the device-types. You are correct, modules do not have slugs generally
