### ISSUE TITLE
SSL Problems 

### ISSUE THREAD

**Issue by stefanvdv** [minitriga/Netbox-Device-Type-Library-Import#16]
Hi, 

I'm getting following error: 

requests.exceptions.SSLError: HTTPSConnectionPool(host='x.x.x.x', port=443): Max retries exceeded with url: /api/dcim/manufacturers/?name=Juniper (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')))

Is it possible to add the option not to validate the cert. (working with self signed certs). 

Kind regards, 

Stefan

**Comment by ndom91** [comment]
You should be able to add `Verify=False` on the end of the request method call, i.e. somethign like `requests.get('https://google.com', verify=False)` in order to disable SSL Cert checking

**Comment by johskar** [comment]
I got it working by changing
`nb = pynetbox.api(nbUrl, token=nbToken)`
in nb-dt-import.py to contain a ssl_verify variable pointing to the cert:
`nb = pynetbox.api(nbUrl, token=nbToken, ssl_verify='<path-to-cert>')`
You can also set `ssl_verify=False` but that'll generate tons of spam in your output about it being disabled so this was cleaner.

Works fine except the warning that my cert has no SAN entries (but that's my own fault)

**Comment by timofmax** [comment]
> I got it working by changing
> `nb = pynetbox.api(nbUrl, token=nbToken)`
> in nb-dt-import.py to contain a ssl_verify variable pointing to the cert:
> `nb = pynetbox.api(nbUrl, token=nbToken, ssl_verify='<path-to-cert>')`
> You can also set `ssl_verify=False` but that'll generate tons of spam in your output about it being disabled so this was cleaner.
> 
> Works fine except the warning that my cert has no SAN entries (but that's my own fault)

Hey @johskar in which format '<path-to-cert>' should be written?
'/root/projects/netbox-docker/localhost+2.pem' ?

**Comment by ndom91** [comment]
@johskar you can also put the following towards the top of your file to silence the warning output and also not have to go through the trouble of generating your own certs, etc.

```python
import urllib3

urllib3.disable_warnings()
```
