### ISSUE TITLE
doesn't import environment vars

### ISSUE THREAD

**Issue by timofmax** [minitriga/Netbox-Device-Type-Library-Import#18]
didn't importing environment vars REPO_URL, NETBOX_URL
for smooth workflow additionally to give manual input() could be an option

<img width="1208" alt="Screenshot 2021-03-18 at 22 55 28" src="https://user-images.githubusercontent.com/10184304/111702830-24665180-883d-11eb-84f0-016faa385f30.png">

**Comment by minitriga** [comment]
Yes this would be a good idea. Will look at implementing it.

**Comment by dmcken** [comment]
This was implemented in the settings.py so this issue can be close I assume.
