### ISSUE TITLE
Docker Build Issue - conflict with urllib3

### ISSUE THREAD

**Issue by silvanet123** [minitriga/Netbox-Device-Type-Library-Import#28]
I rand the docker build and get the following results

docker build -t netbox-devicetype-import-library .
[+] Building 16.8s (9/11)
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 334B                                       0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/python:3.9-alpine       2.4s
 => [auth] library/python:pull token for registry-1.docker.io              0.0s
 => [1/6] FROM docker.io/library/python:3.9-alpine@sha256:7e6fd737db2c21a  1.9s
 => => resolve docker.io/library/python:3.9-alpine@sha256:7e6fd737db2c21a  0.0s
 => => sha256:7e6fd737db2c21aabba823d61e141f706fce21f47b7 1.65kB / 1.65kB  0.0s
 => => sha256:3e7e8a57a959c393797f0c90fa7b0fdbf7a40c4a274 1.37kB / 1.37kB  0.0s
 => => sha256:2af55166a4810d5124e4e879705be7ee6f51a2e3829 7.17kB / 7.17kB  0.0s
 => => sha256:5843afab387455b37944e709ee8c78d7520df80f8d0 2.81MB / 2.81MB  0.5s
 => => sha256:2dfaacf7024eb3bb4c2e67a960e5c65425a95a0 656.34kB / 656.34kB  0.2s
 => => sha256:2dbba127c6aabc2f949cd9713071cadc28e9702ef 11.47MB / 11.47MB  0.5s
 => => sha256:1a467efa2204a8af22ba6cf25e6fe11c6cf8be07b0b5adf 230B / 230B  0.4s
 => => sha256:8b09d69ece5fb7222ff7bd97f4d2d4a3c986974979f 2.36MB / 2.36MB  0.6s
 => => extracting sha256:5843afab387455b37944e709ee8c78d7520df80f8d01cf7f  0.2s
 => => extracting sha256:2dfaacf7024eb3bb4c2e67a960e5c65425a95a09a7a49298  0.1s
 => => extracting sha256:2dbba127c6aabc2f949cd9713071cadc28e9702ef6fdb427  0.5s
 => => extracting sha256:1a467efa2204a8af22ba6cf25e6fe11c6cf8be07b0b5adfa  0.0s
 => => extracting sha256:8b09d69ece5fb7222ff7bd97f4d2d4a3c986974979f8d81a  0.2s
 => [internal] load build context                                          0.0s
 => => transferring context: 16.76kB                                       0.0s
 => [2/6] COPY requirements.txt .                                          0.2s
 => [3/6] RUN apk add --no-cache git                                       1.4s
 => ERROR [4/6] RUN pip3 install -r requirements.txt                      10.8s
------
 > [4/6] RUN pip3 install -r requirements.txt:
#9 2.109 Collecting certifi==2019.11.28
#9 2.312   Downloading certifi-2019.11.28-py2.py3-none-any.whl (156 kB)
#9 2.388 Collecting chardet==3.0.4
#9 2.405   Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
#9 2.445 Collecting gitdb2==3.0.2
#9 2.493   Downloading gitdb2-3.0.2-py2.py3-none-any.whl (63 kB)
#9 2.566 Collecting GitPython==3.0.8
#9 2.586   Downloading GitPython-3.0.8-py3-none-any.whl (450 kB)
#9 2.642 Collecting idna==2.8
#9 2.659   Downloading idna-2.8-py2.py3-none-any.whl (58 kB)
#9 2.763 Collecting progressbar2==3.47.0
#9 2.780   Downloading progressbar2-3.47.0-py2.py3-none-any.whl (24 kB)
#9 2.868 Collecting pynetbox==4.2.5
#9 2.885   Downloading pynetbox-4.2.5.tar.gz (46 kB)
#9 4.059 Collecting python-utils==2.3.0
#9 4.102   Downloading python_utils-2.3.0-py2.py3-none-any.whl (12 kB)
#9 4.183 Collecting PyYAML==5.4
#9 4.201   Downloading PyYAML-5.4.tar.gz (174 kB)
#9 4.578   Installing build dependencies: started
#9 8.594   Installing build dependencies: finished with status 'done'
#9 8.597   Getting requirements to build wheel: started
#9 9.890   Getting requirements to build wheel: finished with status 'done'
#9 9.892     Preparing wheel metadata: started
#9 10.17     Preparing wheel metadata: finished with status 'done'
#9 10.25 Collecting requests==2.22.0
#9 10.26   Downloading requests-2.22.0-py2.py3-none-any.whl (57 kB)
#9 10.30 Collecting six==1.14.0
#9 10.32   Downloading six-1.14.0-py2.py3-none-any.whl (10 kB)
#9 10.35 Collecting smmap2==2.0.5
#9 10.36   Downloading smmap2-2.0.5-py2.py3-none-any.whl (24 kB)
#9 10.43 Collecting urllib3==1.26.5
#9 10.45   Downloading urllib3-1.26.5-py2.py3-none-any.whl (138 kB)
#9 10.51 Collecting python-dotenv==0.15.0
#9 10.52   Downloading python_dotenv-0.15.0-py2.py3-none-any.whl (18 kB)
#9 10.53 Requirement already satisfied: wheel==0.36.2 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 15)) (0.36.2)
#9 10.59 INFO: pip is looking at multiple versions of pyyaml to determine which version is compatible with other requirements. This could take a while.
#9 10.59 INFO: pip is looking at multiple versions of python-utils to determine which version is compatible with other requirements. This could take a while.
#9 10.59 INFO: pip is looking at multiple versions of pynetbox to determine which version is compatible with other requirements. This could take a while.
#9 10.59 INFO: pip is looking at multiple versions of progressbar2 to determine which version is compatible with other requirements. This could take a while.
#9 10.60 INFO: pip is looking at multiple versions of idna to determine which version is compatible with other requirements. This could take a while.
#9 10.60 INFO: pip is looking at multiple versions of gitpython to determine which version is compatible with other requirements. This could take a while.
#9 10.60 INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
#9 10.60 INFO: pip is looking at multiple versions of gitdb2 to determine which version is compatible with other requirements. This could take a while.
#9 10.60 INFO: pip is looking at multiple versions of chardet to determine which version is compatible with other requirements. This could take a while.
#9 10.60 INFO: pip is looking at multiple versions of certifi to determine which version is compatible with other requirements. This could take a while.
#9 10.60 ERROR: Cannot install -r requirements.txt (line 10) and urllib3==1.26.5 because these package versions have conflicting dependencies.
#9 10.60
#9 10.60 The conflict is caused by:
#9 10.60     The user requested urllib3==1.26.5
#9 10.60     requests 2.22.0 depends on urllib3!=1.25.0, !=1.25.1, <1.26 and >=1.21.1
#9 10.60
#9 10.60 To fix this you could try to:
#9 10.60 1. loosen the range of package versions you've specified
#9 10.60 2. remove package versions to allow pip attempt to solve the dependency conflict
#9 10.60
#9 10.60 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
#9 10.61 WARNING: You are using pip version 21.2.2; however, version 21.2.3 is available.
#9 10.61 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
------
executor failed running [/bin/sh -c pip3 install -r requirements.txt]: exit code: 1

**Comment by mickaelbeaudry** [comment]
I had the same issue, so I reverted this PR (https://github.com/minitriga/Netbox-Device-Type-Library-Import/pull/25/files) on my machine and it did build the docker image. 

Essentially I did change requirements.txt, the line of urllib3 and I did revert to version 1.25.8 instead of 1.26.5

Hope this helps you @silvanet123 to get around the problem.

I'm not qualified enough to propose a better solution so I will let @minitriga decide on what are the next steps ;-)
