### ISSUE TITLE
Issue importing

### ISSUE THREAD

**Issue by Potasio101** [minitriga/Netbox-Device-Type-Library-Import#38]
venv) ubuntu@primary:~/Netbox-Device-Type-Library-Import$ ./nb-dt-import.py --vendors CISCO
Package devicetype-library is already installed, updating /home/ubuntu/Netbox-Device-Type-Library-Import/repo
Traceback (most recent call last):
  File "./nb-dt-import.py", line 446, in <module>
    main()
  File "./nb-dt-import.py", line 417, in main
    update_package('./repo')
TypeError: update_package() missing 1 required positional argument: 'branch'

**Comment by suom1** [comment]
I have the same problem, however it's only a problem if you have a existing `repo` directory.
Works fine if you remove the `repo` directory.
