### ISSUE TITLE
invalid syntax line 16

### ISSUE THREAD

**Issue by Trev-W** [minitriga/Netbox-Device-Type-Library-Import#5]
I get the following eror when trying to run this script
 
> File "nb-dt-import.py", line 16
>     def update_package(path: str):
>                            ^
> SyntaxError: invalid syntax

**Comment by ndom91** [comment]
Works for me, are you running it with python2 or some other unrelated unsupported version of python perhaps?

**Comment by Trev-W** [comment]
No, python3 on debian 10

**Comment by Trev-W** [comment]
running `python3 nb-dt-import.py` solved the issue.

Cheers
