### ISSUE TITLE
Python tuple error

### ISSUE THREAD

**Issue by rheadrick1** [minitriga/Netbox-Device-Type-Library-Import#50]
trying to use the docker image, I get the following:
**Package Installed https://github.com/netbox-community/devicetype-library.git
No Vendors Specified, Gathering All Device-Types
82 Vendors Found
1778 Device-Types Found
Traceback (most recent call last):
  File "/app/nb-dt-import.py", line 447, in <module>
    main()
  File "/app/nb-dt-import.py", line 436, in main
    createManufacturers(vendors, nb)
  File "/app/nb-dt-import.py", line 100, in createManufacturers
    print(f'Manufacturer Created: {man.name} - '
AttributeError: 'tuple' object has no attribute 'name'**

**Comment by butterfr** [comment]
Hello,
I had the exact same issue. The reason mine was messed up was because the url was https://example.com rather than https://example.com/ When i added the slash after the url it connected and everything else worked perfectly. Felt like an idiot after figuring it out lol

**Comment by minitriga** [comment]
^^
