### ISSUE TITLE
Module bays and types import

### ISSUE THREAD

**Issue by dmcken** [minitriga/Netbox-Device-Type-Library-Import#51]
Just checking whats the status of this?

I'm seeing modules in the [devicetype-library](https://github.com/netbox-community/devicetype-library) but this tool isn't importing them.

I don't mind working on it or contributing to this if no one else is working on it.

**Comment by dmcken** [comment]
Just want to know if I should take up the task or if someone else is already working on it.

**Comment by arcticash** [comment]
I was just looking for a solution to this exact problem, I've run a full import successfully yet none of the Device Types have module bays, and none of the Module types are imported.

Looks like this repo hasn't been updates in 8+ months so not sure if this project has been abandoned :(

**Comment by ndom91** [comment]
Are "module bays" and "module types" new models in Netbox? If so, this importer will have to be updated. Otherwise, its up to the folks maintaining the entries in the Netbox Device Type library to add accurate info

**Comment by arcticash** [comment]
> Are "module bays" and "module types" new models in Netbox? If so, this importer will have to be updated. Otherwise, its up to the folks maintaining the entries in the Netbox Device Type library to add accurate info 

Not sure, it's noted in the device type library repo that they are supported as of v3.2, not really sure how to use the definition's without the importer though!

**Comment by ndom91** [comment]
@arcticash yeah so it looks like moduletypes were added as of `3.2.0` (See: https://github.com/netbox-community/netbox/releases/tag/v3.2.0).

There have also been a good amt of netbox REST API updates in the latest few releases it looks like.

That means this importer library could definitely use a bit of a clean-up to bring it back up-to-date with the latest Netbox releases. 

If anyone has the time and/or motivation to open a PR, I'm sure @minitriga would be very grateful

**Comment by dmcken** [comment]
Pull request available at:
https://github.com/minitriga/Netbox-Device-Type-Library-Import/pull/52

**Comment by minitriga** [comment]
Thank you @dmcken
