### ISSUE TITLE
SSL Certificate issues

### ISSUE THREAD

**Issue by ekasaj** [minitriga/Netbox-Device-Type-Library-Import#53]
When running the script, at first I encountered the now obvious issue of a self signed certificate, but then, after installing a legit certificate I still get an error:
**Max retries exceeded with url: /api/dcim/manufacturers/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: **CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

The certificate is correct, and chain seems present.
Can you help me fix this?

Thanks

Netbox v3.3.1

**Comment by ndom91** [comment]
There should be an ignoreSsl flag you can pass 

See: https://github.com/minitriga/Netbox-Device-Type-Library-Import/pull/30

**Comment by ekasaj** [comment]
Yes. That's what helped. Changed both options to False and it worked. But still, it shouldn't fail with a correct certificate.

Anyway, thanks a lot, this script is great.

Cheers.
