### ISSUE TITLE
SSL Certificate issues

### ISSUE THREAD

**Issue by EnigmaDR** [minitriga/Netbox-Device-Type-Library-Import#54]
Hi
When running this script i get a ssl error:
**Max retries exceeded with url: /api/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: **CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))
I have tried setting IGNORE_SSL_ERRORS=True in the .env file, but i still get the same error.
i do not get any ssl error when i curl the site

Can you help me fix this?

Thanks

Netbox v3.3.2 with nginx as proxy.

**Comment by W3AXL** [comment]
Can confirm same issue occurs for me, except I'm using apache as my proxy.

```

**Comment by ndom91** [comment]
Found this - https://github.com/psf/requests/issues/3829

Can you check that the `REQUESTS_CA_BUNDLE` env var isn't set in your environments?

**Comment by ndom91** [comment]
Otherwise, a nice user also provided a little session wrapper class we coudl implement

https://github.com/psf/requests/issues/3829#issuecomment-275603654

**Comment by EnigmaDR** [comment]
Hi thanks for your replay, when i set `REQUESTS_CA_BUNDLE` to the path of my ca cert it work with ssl
