### ISSUE TITLE
{"detail":"Invalid token"}

### ISSUE THREAD

**Issue by Trev-W** [minitriga/Netbox-Device-Type-Library-Import#6]
Running the script results in the above error - it reads the vendor and device and then spits this out, even though the NETBOX_TOKEN was copied from opt/netbox/netbox/netbox/configuration.py

`python3 nb-dt-import.py --vendor HPE
Pulled Repo
Package devicetype-library is already installed, updating
Vendor Specified, Gathering All Matching Device-Types
1 Vendors Found
3 Device-Types Found
{"detail":"Invalid token"}
{"detail":"Invalid token"}
{"detail":"Invalid token"}
{"detail":"Invalid token"}
---
0 devices created
0 interfaces/ports updated
0 manufacturers created`

**Comment by ndom91** [comment]
Have you given this token write rights in Netbox?

**Comment by Trev-W** [comment]
Sorry Nico, is that the REMOTE_AUTH_ENABLED setting?

**Comment by ndom91** [comment]
Sorry what do you mean you copied the token from the `configuration.py` file?

You have to generate an API token in the user settings, like so:

![image](https://user-images.githubusercontent.com/7415984/98469779-ecd9ff80-21e1-11eb-9ff8-818148681b0c.png)

![image](https://user-images.githubusercontent.com/7415984/98469792-01b69300-21e2-11eb-8348-7ffe2d2fd15f.png)


Then select "Add a token" at the bottom of the page

And make sure "Write Enabled" is checked. 

![image](https://user-images.githubusercontent.com/7415984/98469821-21e65200-21e2-11eb-861f-7847f6d3a307.png)

The generated token is what you have to use with this script.

**Comment by Trev-W** [comment]
Thank you very much Nico I was exporting the SECRET_KEY 🤦‍♂️ Sent from Mail for Windows 10 From: Nico DominoSent: Sunday, 8 November 2020 11:48 PMTo: minitriga/Netbox-Device-Type-Library-ImportCc: Trev-W; AuthorSubject: Re: [minitriga/Netbox-Device-Type-Library-Import] {"detail":"Invalid token"} (#6) Sorry what do you mean you copied the token from the configuration.py file?You have to generate an API token in the user settings, like so:Then select "Add a token" at the bottom of the pageAnd make sure "Write Enabled" is checked.The generated token is what you have to use with this script.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 



	
		
			
				
			
		
		
			
				This email has been checked for viruses by Avast antivirus software.
				www.avast.com
