### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by fgunno** [minitriga/Netbox-Device-Type-Library-Import#9]
I got these error when running the script:

python nb-dt-import.py
  File "nb-dt-import.py", line 15
    def update_package(path: str):
                           ^
SyntaxError: invalid syntax

**Comment by ndom91** [comment]
Try running it with `python3` instead of `python`, I have a feeling your `python` is still symlinked to `python2` (which you can double check by running `which python`).

**Comment by fgunno** [comment]
Thanks its worked!





[signature_1958969811]

Frédéric Gélinas
Responsable Infrastructure Cloud
Consultant Technique Senior
VMCE


[signature_2135354683]<https://www.facebook.com/NousSommesUNNO/> [signature_1571478130] <https://www.linkedin.com/in/frederic-gelinas-b6b4216a>  [signature_1925851243] <https://www.unno.ca/>

[signature_1447597756] [signature_2026244884]
Question technique / Besoin de support?
Veuillez communiquer avec le 1-866-988-8666 - Poste 1 / via courriel à support@unno.ca<mailto:support@unno.ca>


De : Nico Domino <notifications@github.com>
Répondre à : minitriga/Netbox-Device-Type-Library-Import <reply@reply.github.com>
Date : mercredi 18 novembre 2020 à 06:53
À : minitriga/Netbox-Device-Type-Library-Import <Netbox-Device-Type-Library-Import@noreply.github.com>
Cc : Frédéric Gélinas <fg@unno.ca>, Author <author@noreply.github.com>
Objet : Re: [minitriga/Netbox-Device-Type-Library-Import] Invalid Syntax (#9)


Try running it with python3 instead of python, I have a feeling your python is still symlinked to python2 (which you can double check by running which python).

**Comment by ndom91** [comment]
@minitriga this can be closed

**Comment by minitriga** [comment]
@ndom91 Thank you.
